language: cpp
compiler: clang

addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.8
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.8

notifications:
  email: false

before_script: "make local_deploy -C cpp/org/modcpp/bluckbuild"
script: "./bin/bluck test //cpptests/org/modcpp:unittests"
